### ISSUE TITLE
Which site?

### ISSUE THREAD

**Issue by aadrian** [x-stream/xsite#2]
Hi,

for XSite there seems to be this repository https://github.com/x-stream/xsite but also https://github.com/codehaus/xsite-git  and also https://github.com/codehaus/xsite (this one seems to have different IDs for same transactions)

Which one to use, fork, send PRs/issues to?

Thank you.

**Comment by joehni** [comment]
See http://markmail.org/search/?q=xsite
last announcement on the old Codehaus list is the first message in the search list

**Comment by aadrian** [comment]
@joehni what about XStream? Seems to be in the same situation :) .

**Comment by joehni** [comment]
The Github Codehaus repos are all read-only archives. Just in case on of the projects did not jumped board in time.

**Comment by aadrian** [comment]
@joehni thanks for the info.
