### ISSUE TITLE
Option to disable CharacterEscaper? 

### ISSUE THREAD

**Issue by aadrian** [x-stream/xsite#4]
Hi,

Is there a way to disable the CharacterEscaper functionality from the config (so without rebuilding the software) ?

It seems to act independent of the file encoding - even on utf-8 HTML files, thus rendering them useless (for l10 sites that were working with XSite < 1.3)

Thank you.

**Comment by joehni** [comment]
Look into the POM of the distribution subproject of xsite itself, how to configure your own components. Or look in XStream, it does not use the CharacterEscaper also.

**Comment by aadrian** [comment]
@joehni thank you for the hint.
May I update the wiki with this info? Other users also had this problem.

**Comment by joehni** [comment]
XSite has an FAQ on its site: http://x-stream.github.io/xsite/faq.html
The site itself is generated in the distribution subproject - we eat our own dog food :-)

**Comment by aadrian** [comment]
> XSite has an FAQ

OK, I'll add that info in the FAQ section of the site :)
